name: Weer Scraper

on:
  schedule:
    - cron: '30 19,0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes if any
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.io"
          git add weer_verificatie_database.xlsx
          git commit -m "Automatische update van weerdata via scraper" || echo "Geen wijzigingen om te committen"
          git push
